spring:
  cloud:
    gateway:
      routes:
        - id: youtube_route
          uri: https://www.youtube.com/
          predicates:
            - Query=url, youtube

        - id: bilibili_route
          uri: https://www.bilibili.com/
          predicates:
            - Query=url, bilibili

        # target: http://localhost:10000/product/category/list/tree
        # replaced: http://localhost:88/api/product/category/list/tree
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        # target: http://localhost:8000/renren-fast/captcha.jpg
        # replaced: http://localhost:88/api/captcha.jpg
        - id: admin_route
          uri: lb://renren-fast # 负载均衡到指定服务renren-fast
          predicates:
          - Path=/api/**
          filters:
          - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}

